<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PagesMetaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('pages_meta')->insert([
            [
                'id' => 1,
                'ref_id' => 1,
                'ref_key' => 'section_two_title_one',
                'ref_value' => 'Designing spaces, bringing ideas to life',
                'created_at' => '2025-10-01 09:12:44',
                'updated_at' => '2025-10-01 09:12:44',
                'deleted_at' => null,
            ],
            [
                'id' => 2,
                'ref_id' => 1,
                'ref_key' => 'section_two_description_one',
                'ref_value' => 'At Prescott, we don’t just build structures; we craft modern lifestyles. Our team of experts is dedicated to pushing the boundaries of design, integrating the latest technologies to create spaces that adapt to the needs of tomorrow.',
                'created_at' => '2025-10-01 09:12:44',
                'updated_at' => '2025-10-01 09:12:44',
                'deleted_at' => null,
            ],
            [
                'id' => 3,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_one_text',
                'ref_value' => 'learn more',
                'created_at' => '2025-10-01 09:29:46',
                'updated_at' => '2025-10-01 09:29:46',
                'deleted_at' => null,
            ],
            [
                'id' => 4,
                'ref_id' => 1,
                'ref_key' => 'section_two_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => '2025-10-01 09:29:47',
                'updated_at' => '2025-10-01 09:29:47',
                'deleted_at' => null,
            ],
            [
                'id' => 5,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_one',
                'ref_value' => '19+',
                'created_at' => '2025-10-01 09:34:01',
                'updated_at' => '2025-10-01 09:34:01',
                'deleted_at' => null,
            ],
            [
                'id' => 6,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_one_title',
                'ref_value' => 'Years of Experience',
                'created_at' => '2025-10-01 09:34:01',
                'updated_at' => '2025-10-01 09:34:01',
                'deleted_at' => null,
            ],
            [
                'id' => 7,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_two',
                'ref_value' => 'Units Delivered',
                'created_at' => '2025-10-01 09:38:20',
                'updated_at' => '2025-10-01 04:46:55',
                'deleted_at' => null,
            ],
            [
                'id' => 8,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_two',
                'ref_value' => 'Units Delivered',
                'created_at' => '2025-10-01 09:38:20',
                'updated_at' => '2025-10-01 09:38:20',
                'deleted_at' => null,
            ],
            [
                'id' => 9,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_three',
                'ref_value' => '1,500+',
                'created_at' => '2025-10-01 09:44:30',
                'updated_at' => '2025-10-01 04:47:18',
                'deleted_at' => null,
            ],
            [
                'id' => 10,
                'ref_id' => 1,
                'ref_key' => 'section_two_stats_three_title',
                'ref_value' => 'Units Launched',
                'created_at' => '2025-10-01 09:44:30',
                'updated_at' => '2025-10-01 09:44:30',
                'deleted_at' => null,
            ],
            [
                'id' => 11,
                'ref_id' => 1,
                'ref_key' => 'section_three_heading_one',
                'ref_value' => 'Signature Projects',
                'created_at' => '2025-10-01 09:56:56',
                'updated_at' => '2025-10-01 09:56:56',
                'deleted_at' => null,
            ],
            [
                'id' => 12,
                'ref_id' => 1,
                'ref_key' => 'section_three_button_one_text',
                'ref_value' => 'learn more',
                'created_at' => '2025-10-01 09:56:56',
                'updated_at' => '2025-10-01 09:56:56',
                'deleted_at' => null,
            ],
            [
                'id' => 13,
                'ref_id' => 1,
                'ref_key' => 'section_three_button_one_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => '2025-10-01 09:59:36',
                'updated_at' => '2025-10-01 09:59:36',
                'deleted_at' => null,
            ],
            [
                'id' => 14,
                'ref_id' => 1,
                'ref_key' => 'section_four_heading_one',
                'ref_value' => 'Verano by prescott',
                'created_at' => '2025-10-01 10:12:21',
                'updated_at' => '2025-10-01 10:12:21',
                'deleted_at' => null,
            ],
            [
                'id' => 15,
                'ref_id' => 1,
                'ref_key' => 'section_four_sub_heading_one',
                'ref_value' => 'Palm Jumeirah, Dubai',
                'created_at' => '2025-10-01 10:12:21',
                'updated_at' => '2025-10-01 10:12:21',
                'deleted_at' => null,
            ],
            [
                'id' => 16,
                'ref_id' => 1,
                'ref_key' => 'section_four_key_one',
                'ref_value' => 'Area',
                'created_at' => '2025-10-01 10:15:45',
                'updated_at' => '2025-10-01 10:15:45',
                'deleted_at' => null,
            ],
            [
                'id' => 17,
                'ref_id' => 1,
                'ref_key' => 'section_four_value_one',
                'ref_value' => '8426.54 m2',
                'created_at' => '2025-10-01 10:15:45',
                'updated_at' => '2025-10-01 10:15:45',
                'deleted_at' => null,
            ],
            [
                'id' => 18,
                'ref_id' => 1,
                'ref_key' => 'section_four_key_two',
                'ref_value' => 'No. of Floors',
                'created_at' => '2025-10-01 10:20:01',
                'updated_at' => '2025-10-01 05:25:13',
                'deleted_at' => null,
            ],
            [
                'id' => 19,
                'ref_id' => 1,
                'ref_key' => 'section_four_value_two',
                'ref_value' => 'g + 12',
                'created_at' => '2025-10-01 10:20:01',
                'updated_at' => '2025-10-01 10:20:01',
                'deleted_at' => null,
            ],
            [
                'id' => 20,
                'ref_id' => 1,
                'ref_key' => 'section_four_key_three',
                'ref_value' => 'Building Height',
                'created_at' => '2025-10-01 10:21:31',
                'updated_at' => '2025-10-01 05:25:13',
                'deleted_at' => null,
            ],
            [
                'id' => 21,
                'ref_id' => 1,
                'ref_key' => 'section_four_value_three',
                'ref_value' => '55.4 m',
                'created_at' => '2025-10-01 10:21:31',
                'updated_at' => '2025-10-01 10:21:31',
                'deleted_at' => null,
            ],
            [
                'id' => 22,
                'ref_id' => 1,
                'ref_key' => 'section_four_key_four',
                'ref_value' => 'No. of Apartments',
                'created_at' => '2025-10-01 10:23:09',
                'updated_at' => '2025-10-01 10:23:09',
                'deleted_at' => null,
            ],
            [
                'id' => 23,
                'ref_id' => 1,
                'ref_key' => 'section_four_value_four',
                'ref_value' => '200',
                'created_at' => '2025-10-01 10:23:09',
                'updated_at' => '2025-10-01 10:23:09',
                'deleted_at' => null,
            ],
            [
                'id' => 24,
                'ref_id' => 1,
                'ref_key' => 'section_five_heading',
                'ref_value' => 'Latest Launches',
                'created_at' => '2025-10-01 10:26:01',
                'updated_at' => '2025-10-01 10:26:01',
                'deleted_at' => null,
            ],
            [
                'id' => 25,
                'ref_id' => 1,
                'ref_key' => 'section_five_button_text',
                'ref_value' => 'See all projects',
                'created_at' => '2025-10-01 10:26:01',
                'updated_at' => '2025-10-01 10:26:01',
                'deleted_at' => null,
            ],
            [
                'id' => 26,
                'ref_id' => 1,
                'ref_key' => 'section_five_button_link',
                'ref_value' => 'https://google.com',
                'created_at' => '2025-10-01 10:30:05',
                'updated_at' => '2025-10-01 10:30:05',
                'deleted_at' => null,
            ],
            [
                'id' => 27,
                'ref_id' => 1,
                'ref_key' => 'section_six_heading',
                'ref_value' => 'Design. Define. Live.',
                'created_at' => '2025-10-01 10:35:07',
                'updated_at' => '2025-10-01 10:35:07',
                'deleted_at' => null,
            ],
            [
                'id' => 28,
                'ref_id' => 1,
                'ref_key' => 'section_seven_heading',
                'ref_value' => 'Designing spaces, bringing ideas to life',
                'created_at' => '2025-10-01 10:36:57',
                'updated_at' => '2025-10-01 10:36:57',
                'deleted_at' => null,
            ],
            [
                'id' => 29,
                'ref_id' => 1,
                'ref_key' => 'section_seven_button_text',
                'ref_value' => 'Experiences',
                'created_at' => '2025-10-01 10:36:57',
                'updated_at' => '2025-10-01 10:36:57',
                'deleted_at' => null,
            ],
            [
                'id' => 30,
                'ref_id' => 1,
                'ref_key' => 'section_seven_button_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => '2025-10-01 10:40:14',
                'updated_at' => '2025-10-01 10:40:14',
                'deleted_at' => null,
            ],
            [
                'id' => 31,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_one_title',
                'ref_value' => 'Craftsmanship',
                'created_at' => '2025-10-01 10:41:59',
                'updated_at' => '2025-10-01 10:41:59',
                'deleted_at' => null,
            ],
            [
                'id' => 32,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_two_title',
                'ref_value' => 'Design Detail',
                'created_at' => '2025-10-01 10:41:59',
                'updated_at' => '2025-10-01 10:41:59',
                'deleted_at' => null,
            ],
            [
                'id' => 33,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_three_title',
                'ref_value' => 'Community Spaces',
                'created_at' => '2025-10-01 10:44:41',
                'updated_at' => '2025-10-01 10:44:41',
                'deleted_at' => null,
            ],
            [
                'id' => 34,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_one_desc',
                'ref_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod...',
                'created_at' => '2025-10-01 10:44:41',
                'updated_at' => '2025-10-01 10:44:41',
                'deleted_at' => null,
            ],
            [
                'id' => 35,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_two_desc',
                'ref_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod...',
                'created_at' => '2025-10-01 10:48:06',
                'updated_at' => '2025-10-01 10:48:06',
                'deleted_at' => null,
            ],
            [
                'id' => 36,
                'ref_id' => 1,
                'ref_key' => 'section_seven_content_three_desc',
                'ref_value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod...',
                'created_at' => '2025-10-01 10:48:06',
                'updated_at' => '2025-10-01 10:48:06',
                'deleted_at' => null,
            ],
            [
                'id' => 37,
                'ref_id' => 1,
                'ref_key' => 'section_eight_heading',
                'ref_value' => 'News & Insights',
                'created_at' => '2025-10-01 11:05:15',
                'updated_at' => '2025-10-01 11:05:15',
                'deleted_at' => null,
            ],
            [
                'id' => 38,
                'ref_id' => 1,
                'ref_key' => 'section_eight_button_text',
                'ref_value' => 'See all resources',
                'created_at' => '2025-10-01 11:05:15',
                'updated_at' => '2025-10-01 11:05:15',
                'deleted_at' => null,
            ],
            [
                'id' => 39,
                'ref_id' => 1,
                'ref_key' => 'section_eight_button_link',
                'ref_value' => 'https://www.google.com/',
                'created_at' => '2025-10-01 11:07:48',
                'updated_at' => '2025-10-01 11:07:48',
                'deleted_at' => null,
            ],
        ]);
    }
}

